name       : haskell-fsnotify
version    : 0.2.1
release    : 1
source     :
    - http://hackage.haskell.org/package/fsnotify-0.2.1/fsnotify-0.2.1.tar.gz : ebcf1b7bd825f269510850f20508a2ba0f640a41af08de0c171d8ba24618542b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Cross platform library for file creation, modification, and deletion notification.
description: |
    Cross platform library for file creation, modification, and deletion notification.
builddeps  :
    - haskell-cabal-install
    - haskell-hinotify
    - haskell-unix-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
