name       : haskell-fsnotify
version    : 0.2.1.2
release    : 2
source     :
    - https://hackage.haskell.org/package/fsnotify-0.2.1.2/fsnotify-0.2.1.2.tar.gz : d7cb2fcbb60b1acdb217ecd560ccab98438560cf51310bd7d239ecf2f4f4048d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Cross platform library for file creation, modification, and deletion notification.
description: |
    Cross platform library for file creation, modification, and deletion notification.
builddeps  :
    - haskell-cabal-install
    - haskell-hinotify
    - haskell-unix-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
