name       : haskell-fsnotify
version    : 0.3.0.1
release    : 3
source     :
    - https://hackage.haskell.org/package/fsnotify-0.3.0.1/fsnotify-0.3.0.1.tar.gz : ded2165f72a2b4971f941cb83ef7f58b200e3e04159be78da55ba6c5d35f6da5
license    : BSD-3-Clause
component  : programming.haskell
summary    : Cross platform library for file creation, modification, and deletion notification.
description: |
    Cross platform library for file creation, modification, and deletion notification.
builddeps  :
    - haskell-cabal-install
    - haskell-hinotify-devel
    - haskell-shelly-devel
rundeps    :
    - devel:
        - haskell-hinotify-devel
        - haskell-shelly-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
